name = "firstleads-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "firstleads-crm"
database_id = "0e65a67e-7f1b-48dc-801d-482592643149"

